/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem.employeepkg;

//import static Interfaces.Emp_Info.dob_box;
import managementsystem.*;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BBR
 */
public class All_Emp extends javax.swing.JFrame {

    Emp_Info e = new Emp_Info();
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form All_Emp
     */
    public All_Emp() {
        initComponents();
        try {
            conn = DB.mycon();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(All_Emp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(All_Emp.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableLoad();
    }

    public void tableLoad() {
        try {
//            String s = "select `id`, `first_name`, `surname`, `Dob`, `Email`, `Telephone`, `Address`, `Department`, `Salary`, `Post_code`, `Designation`, `Status`, `Date_hired`, `gender`, `pwd` from `staff_information`";
            String s = "select * from `staff_information`";

            pst = conn.prepareStatement(s);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search_box = new javax.swing.JTextField();
        Btn_update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        search_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        search_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_boxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_boxKeyReleased(evt);
            }
        });

        Btn_update.setText("Update");
        Btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_updateActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel2.setText("Search Employee :");

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 180, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void search_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_boxKeyPressed

    private void search_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyReleased
        // TODO add your handling code here:

        String a = search_box.getText();
        String b = "";
        if (search_box.getText().equals(b)) {
            tableLoad();
        } else {
            try {
                String sql = "SELECT * FROM `staff_information` WHERE id='" + a + "'";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_search_boxKeyReleased

    private void Btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_updateActionPerformed
        // TODO add your handling code here:

        int r = jTable1.getSelectedRow();
        if (r < 0) {
            JOptionPane.showMessageDialog(null, "Select a Row to Update !");

        } else {
            this.dispose();
            Emp_Info e = new Emp_Info();
            e.setVisible(true);

            String add1 = jTable1.getValueAt(r, 0).toString();
            String add2 = jTable1.getValueAt(r, 1).toString();
            String add3 = jTable1.getValueAt(r, 2).toString();
            String add4 = jTable1.getValueAt(r, 3).toString();
            String add5 = jTable1.getValueAt(r, 4).toString();
            String add6 = jTable1.getValueAt(r, 5).toString();
            String add7 = jTable1.getValueAt(r, 6).toString();
            String add8 = jTable1.getValueAt(r, 7).toString();
            String add9 = jTable1.getValueAt(r, 8).toString();
            String add10 = jTable1.getValueAt(r, 9).toString();
            String add11 = jTable1.getValueAt(r, 10).toString();
            String add12 = jTable1.getValueAt(r, 11).toString();
            String add13 = jTable1.getValueAt(r, 12).toString();
            String add14 = jTable1.getValueAt(r, 13).toString();
            String add15 = jTable1.getValueAt(r, 14).toString();
            // String add16 = jTable1.getValueAt(r, 15).toString();
            String add17 = jTable1.getValueAt(r, 16).toString();
            String add18 = jTable1.getValueAt(r, 17).toString();

            Emp_Info.id_box.setText(add1);
            Emp_Info.firstname_box.setText(add2);
            Emp_Info.surname_box.setText(add3);
            Emp_Info.dob_box.setText(add4);
            Emp_Info.email_box.setText(add5);
            Emp_Info.contact_box.setText(add6);
            Emp_Info.address_box.setText(add7);

            if (add8.equals("Finance")) {
                Emp_Info.c_dep.setSelectedIndex(1);
            } else if (add8.equals("HR")) {
                Emp_Info.c_dep.setSelectedIndex(2);
            } else if (add8.equals("Products")) {
                Emp_Info.c_dep.setSelectedIndex(3);
            } else {
                Emp_Info.c_dep.setSelectedIndex(0);
            }

//        Emp_Info.sallary_box.setText(add9);
            Emp_Info.postcode_box.setText(add10);
            Emp_Info.desig_box.setText(add11);

            if (add12.equals("Active")) {
                Emp_Info.c_status.setSelectedIndex(0);
            } else {
                Emp_Info.c_status.setSelectedIndex(1);
            }

            Emp_Info.datehired_box.setText(add13);
            Emp_Info.job_box.setText(add14);
            if (add15.equals("Male")) {
                Emp_Info.r_male.setSelected(true);
            } else {
                Emp_Info.r_female.setSelected(true);
            }
            Emp_Info.pass.setText(add17);
//        Emp_Info.ot_box.setText(add18);
        }

    }//GEN-LAST:event_Btn_updateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        if (r < 0) {
            JOptionPane.showMessageDialog(null, "Select a Row to Delete !");

        } else {
            String id = jTable1.getValueAt(r, 0).toString();

            try {
                int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Delete?");
                if (x == 0) {
                    String sql = "DELETE FROM `staff_information` WHERE `id`=('" + id + "')";
                    pst = conn.prepareStatement(sql);
                    pst.execute();
                    tableLoad();
                    JOptionPane.showMessageDialog(null, "Deleted !");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Emp_Info a = new Emp_Info();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(All_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(All_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(All_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(All_Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new All_Emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_update;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField search_box;
    // End of variables declaration//GEN-END:variables
}
