/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem.employeepkg;

import com.toedter.calendar.JDateChooser;
import managementsystem.*;
//import ems.validation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BBR
 */
public class Emp_Info extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    private String gender = "";
    private ImageIcon format = null;
    String filename = null;
    String aa = null;
    int w = 0;
    byte[] person_image = null;
    String i = null;
    String dd = null;

    // data
//    private int Employee_ID;
//    private String First_Name;
//    private String Surname;
//    private String Gender;
    /**
     * Creates new form Emp_Info
     */
    public Emp_Info() {
        initComponents();
        try {
            conn = DB.mycon();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Emp_Info.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Emp_Info.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void clear() {
        id_box.setText("");
        firstname_box.setText("");
        surname_box.setText("");
        dob_box.setText("");
        email_box.setText("");
        contact_box.setText("");
        address_box.setText("");
        postcode_box.setText("");
        c_dep.setSelectedIndex(0);
        r_male.setSelected(false);
        r_female.setSelected(false);
        desig_box.setText("");
        datehired_box.setText("");
//        sallary_box.setText("");
        job_box.setText("");
        c_status.setSelectedIndex(0);
//        date_hire_box.setText("");
        id_box.setText("");
        pass.setText("");
        search_box.setText("");
        img.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        surname_box = new javax.swing.JTextField();
        firstname_box = new javax.swing.JTextField();
        email_box = new javax.swing.JTextField();
        contact_box = new javax.swing.JTextField();
        address_box = new javax.swing.JTextField();
        postcode_box = new javax.swing.JTextField();
        desig_box = new javax.swing.JTextField();
        job_box = new javax.swing.JTextField();
        r_female = new javax.swing.JRadioButton();
        r_male = new javax.swing.JRadioButton();
        search_box = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        c_dep = new javax.swing.JComboBox<>();
        c_status = new javax.swing.JComboBox<>();
        id_box = new javax.swing.JLabel();
        datehired_box = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        dob_box = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(943, 587));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Registration");

        jButton7.setText("Main Menu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 525, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jLabel1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 943, -1));

        jLabel3.setText("Employee ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setText("First Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel5.setText("Surname");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel6.setText("Gender");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel7.setText("Date of birth : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel8.setText("Email :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel9.setText("Contact :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel10.setText("Address :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel11.setText("Postcode :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel12.setText("Department :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel13.setText("Designation :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel14.setText("Date Hired :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabel16.setText("Job Title :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jLabel17.setText("Status :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));
        jPanel1.add(surname_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 165, -1));
        jPanel1.add(firstname_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 165, -1));
        jPanel1.add(email_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 165, -1));
        jPanel1.add(contact_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 165, -1));
        jPanel1.add(address_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 165, -1));
        jPanel1.add(postcode_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 165, -1));
        jPanel1.add(desig_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 168, -1));
        jPanel1.add(job_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 165, -1));

        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(r_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel1.add(r_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        search_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_boxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_boxKeyReleased(evt);
            }
        });
        jPanel1.add(search_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 100, 470, -1));

        jLabel2.setText("Search Employee :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 103, -1, -1));

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, 32));

        jButton2.setText("Add Record");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, 32));

        jButton3.setText("Update Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, -1, 32));

        jButton4.setText("Attach");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 260, 32));

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, 32));

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 265, 217));

        c_dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Department", "Finance", "HR", "Products" }));
        jPanel1.add(c_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 170, -1));

        c_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        jPanel1.add(c_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 168, -1));
        jPanel1.add(id_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 160, 165, 20));
        jPanel1.add(datehired_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 170, 20));

        jLabel18.setText("Password :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 165, -1));

        jButton6.setText("View All Employees");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, -1, 32));
        jPanel1.add(dob_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 90, -1));

        jLabel15.setText("(dd/mm/yy)");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, 20));

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(901, 626));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String bsal = "25000";
        String otrate = "500";

        // search is exsist
        try {
            String sql = "SELECT `id` FROM `staff_information` WHERE `id`=('" + id_box.getText() + "')";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));;
            i = jTable1.getValueAt(0, 0).toString();

        } catch (Exception e) {
            System.out.println(e);
        }
//        if (id_box.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "No Data to Add");
//        }

        try {

            validation2 d = new validation2();

            if (validation2.isValidName(firstname_box.getText())
                    && validation2.isValidSurName(surname_box.getText())
                    && validation2.isValidGender(gender)
                    && validation2.isValidBdate(dob_box.getText())
                    && validation2.isValidEmail(email_box.getText())
                    && validation2.isValidPhoneNumber(contact_box.getText())
                    && validation2.isValidPcode(postcode_box.getText())
                    && validation2.isValidDesig(desig_box.getText())
                    && validation2.isValidDept(c_dep.getSelectedItem().toString())) {
                int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to save?");
                if (x == 0) {
                    String sql = "INSERT INTO staff_information (gender,first_name,surname,Dob,Email,Telephone,Address,Department,Salary,Post_code,Designation,Status,job_title,image,pwd,ot_rate)"
                            + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, gender);
                    pst.setString(2, firstname_box.getText());
                    pst.setString(3, surname_box.getText());
                    pst.setString(4, dob_box.getText());
                    pst.setString(5, email_box.getText());
                    pst.setString(6, contact_box.getText());
                    pst.setString(7, address_box.getText());
                    pst.setString(8, c_dep.getSelectedItem().toString());
                    pst.setString(9, bsal);
                    pst.setString(10, postcode_box.getText());
                    pst.setString(11, desig_box.getText());
                    pst.setString(12, c_status.getSelectedItem().toString());
                    pst.setString(13, job_box.getText());
                    pst.setBytes(14, person_image);
                    pst.setString(15, pass.getText());
                    pst.setString(16, otrate);

                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Added");
                    clear();
                }
            } else {

            }

        } catch (HeadlessException | SQLException e) {
            System.out.println(e);
        }
        // FInd max id
        try {
            String sq2 = "SELECT MAX(id) FROM `staff_information`";
            pst = conn.prepareStatement(sq2);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));;
            aa = jTable2.getValueAt(0, 0).toString();
            int q = Integer.parseInt(aa);
            w = q++;
            System.out.println(w);

        } catch (Exception e) {
            System.out.println(e);
        }

        // create attendence table
        try {
            String sq = "CREATE TABLE eat" + w + " (`id` int(255) PRIMARY KEY AUTO_INCREMENT, `count` int(255) NOT NULL,"
                    + " `date` varchar(20) NULL, `in` varchar(20) NULL, `out` varchar(20) NULL, `month` int(20) NOT NULL,"
                    + " `OThours` INT(5) NULL, `status` varchar(20) NULL )";
            System.out.println(sq);

            pst = conn.prepareStatement(sq);
            pst.execute();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = id_box.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Select an Id to Delete !");
        } else {
            try {
                int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Delete?");
                if (x == 0) {
                    String sql = "DELETE FROM `staff_information` WHERE `id`=('" + id + "')";
                    pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Deleted !");
                    clear();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);


    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here: 
        gender = "Female";
        r_male.setSelected(false);
        r_female.setSelected(true);

    }//GEN-LAST:event_r_femaleActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);

        try {
            File image = new File(filename);
            FileInputStream fix = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buff = new byte[1024];

            for (int number; (number = fix.read(buff)) != -1;) {
                bos.write(buff, 0, number);
            }
            person_image = bos.toByteArray();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void search_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyReleased
        // TODO add your handling code here:
        String a = search_box.getText();
        try {
//            Statement s= conn.createStatement();
//            ResultSet rs = s.executeQuery("SELECT * FROM `staff_information` WHERE id='" + a + "'");
//            while (rs.next()){
//            File f1= new File(rs.getString("image"));
//            Image im =ImageIO.read(f1);
//            im=im.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT);
//                        img.setIcon(new ImageIcon(im));
//
//            
//            }
            String sql = "SELECT * FROM `staff_information` WHERE id='" + a + "'";
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

            String id = jTable1.getValueAt(0, 0).toString();
            id_box.setText(id);

            String add2 = jTable1.getValueAt(0, 1).toString();
            firstname_box.setText(add2);

            String add3 = jTable1.getValueAt(0, 2).toString();
            surname_box.setText(add3);

            String add4 = jTable1.getValueAt(0, 3).toString();
            dob_box.setText(add4);

            String add5 = jTable1.getValueAt(0, 4).toString();
            email_box.setText(add5);

            String add15 = jTable1.getValueAt(0, 14).toString();
            if (add15.equals("Male")) {
                r_male.setSelected(true);
                r_female.setSelected(false);
            } else {
                r_female.setSelected(true);
                r_male.setSelected(false);

            }

            String add17 = jTable1.getValueAt(0, 16).toString();
            pass.setText(add17);

            String add6 = jTable1.getValueAt(0, 5).toString();
            contact_box.setText(add6);

            String add7 = jTable1.getValueAt(0, 6).toString();
            address_box.setText(add7);

            String add10 = jTable1.getValueAt(0, 9).toString();
            postcode_box.setText(add10);

            String add8 = jTable1.getValueAt(0, 7).toString();
            switch (add8) {
                case "Products":
                    c_dep.setSelectedIndex(3);
                    break;
                case "Finance":
                    c_dep.setSelectedIndex(1);
                    break;
                case "HR":
                    c_dep.setSelectedIndex(2);
                    break;
                default:
                    c_dep.setSelectedIndex(0);
                    break;
            }

            String add11 = jTable1.getValueAt(0, 10).toString();
            desig_box.setText(add11);

            String add13 = jTable1.getValueAt(0, 12).toString();
            datehired_box.setText(add13);

//            String add9 = jTable1.getValueAt(0, 8).toString();
//            sallary_box.setText(add9);
            String add14 = jTable1.getValueAt(0, 13).toString();
            job_box.setText(add14);

            String add12 = jTable1.getValueAt(0, 11).toString();
            if (add12.equals("Active")) {
                c_status.setSelectedIndex(0);
            } else {
                c_status.setSelectedIndex(1);
            }
//            String add18 = jTable1.getValueAt(0, 17).toString();
//            ot_box.setText(add18);

        }catch (SQLException e) {
            e.printStackTrace();

        }
//
//        try {
//            String sqli = "SELECT * FROM `staff_information` WHERE id=?";
//            pst = conn.prepareStatement(sqli);
//            pst.setString(1, search_box.getText());
//            rs = pst.executeQuery();
//
//            byte[] image = rs.getBytes("image");
//            ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
//            img.setIcon(imageIcon);
//
//        } catch (Exception e) {
//        } finally {
//            try {
//                rs.close();
//                pst.close();
//            } catch (Exception e) {
//            }
//        }
        
// 
//        try {
//            String sqli = "SELECT * FROM `staff_information` WHERE id=?";
//            pst = conn.prepareStatement(sqli);
//            pst.setString(1, search_box.getText());
//            rs = pst.executeQuery();
//
//            byte[] image = rs.getBytes("image");
//            ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
//            img.setIcon(imageIcon);
//            
//        } catch (Exception e) {
//        } finally {
//            try {
//                rs.close();
//                pst.close();
//            } catch (Exception e) {
//            }
//        }

    }//GEN-LAST:event_search_boxKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = id_box.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(null, "Select an Id to Delete !");
        } else {
            try {
//                if (validation.isValidName(firstname_box.getText())
//                        && validation.isValidSurName(surname_box.getText())
//                        && validation.isValidGender(gender)
//                        && validation.isValidBdate(dob_box.getText())
//                        && validation.isValidEmail(email_box.getText())
//                        && validation.isValidPhoneNumber(contact_box.getText())
//                        && validation.isValidPcode(postcode_box.getText())
//                        && validation.isValidDesig(desig_box.getText())
//                        && validation.isValidDept(c_dep.getSelectedItem().toString())) {
//                    
                String val0 = id_box.getText();
                String add1 = firstname_box.getText();
                String add2 = surname_box.getText();
                String add3 = dob_box.getText();
                String add4 = email_box.getText();
                String add5 = contact_box.getText();
                String add6 = address_box.getText();
                String add7 = c_dep.getSelectedItem().toString();
//        String add8 = sallary_box.getText();
                String add9 = postcode_box.getText();
                String add10 = desig_box.getText();
                String add11 = c_status.getSelectedItem().toString();
                String add12 = job_box.getText();
                String add14 = pass.getText();
//        String add15 = date_hire_box.getText();
//        String add16 = ot_box.getText();

                int x = JOptionPane.showConfirmDialog(null, "Do you really want to Update ?");
                if (x == 0) {

                    String sql = "UPDATE `staff_information` SET `first_name`=('" + add1 + "'),`surname`=('" + add2 + "')"
                            + ",`Dob`=('" + add3 + "'),`Email`=('" + add4 + "'),`Telephone`=('" + add5 + "'),`Address`=('" + add6 + "'),"
                            + "`Department`=('" + add7 + "'),`Post_code`=('" + add9 + "')"
                            + ",`Designation`=('" + add10 + "'),`Status`=('" + add11 + "'),"
                            + "`job_title`=('" + add12 + "'),`gender`=('" + gender + "'),`pwd`=('" + add14 + "') "
                            + "WHERE `id`=('" + val0 + "')";
                    pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Updated !");
//                    }
                } else {

                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void search_boxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyPressed

    }//GEN-LAST:event_search_boxKeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        firstname_box.setText("");
        surname_box.setText("");
        dob_box.setText("");
        email_box.setText("");
        contact_box.setText("");
        address_box.setText("");
        postcode_box.setText("");
        c_dep.setSelectedIndex(0);
        r_male.setSelected(false);
        r_female.setSelected(false);
        desig_box.setText("");
        datehired_box.setText("");
//        sallary_box.setText("");
        job_box.setText("");
        c_status.setSelectedIndex(0);
//        date_hire_box.setText("");
        id_box.setText("");
        pass.setText("");
        search_box.setText("");
        img.setIcon(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        All_Emp a1 = new All_Emp();
        a1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        system s = new system();
//        s.setVisible(true);
    new employee().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField address_box;
    public static javax.swing.JComboBox<String> c_dep;
    public static javax.swing.JComboBox<String> c_status;
    public static javax.swing.JTextField contact_box;
    public static javax.swing.JLabel datehired_box;
    public static javax.swing.JTextField desig_box;
    public static javax.swing.JTextField dob_box;
    public static javax.swing.JTextField email_box;
    public static javax.swing.JTextField firstname_box;
    public static javax.swing.JLabel id_box;
    public static javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public static javax.swing.JTextField job_box;
    public static javax.swing.JTextField pass;
    public static javax.swing.JTextField postcode_box;
    public static javax.swing.JRadioButton r_female;
    public static javax.swing.JRadioButton r_male;
    private javax.swing.JTextField search_box;
    public static javax.swing.JTextField surname_box;
    // End of variables declaration//GEN-END:variables
}
