/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem.employeepkg;

import managementsystem.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author BBR
 */
public class sal extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int otHours = 0;
    int punishments = 0;
    int fullDays = 0;
    int HalfDays = 0;
    int month = 0;
    String Eid;
    int TotWorkDays = 0;
    int pay = 0;
    int Netsal;
    String TNetsal;
    int psal = 0;
    int otpay = 0;
    int ot_rate = 0;
    String OtPayment;
    int NBT = 2 / 100;
    int EPF = 2 / 100;
    int ETF = 2 / 100;
    int FullSal = 0;
    int decrements = 0;
    String status;
    int netsal = 0;
    int upsal = 0;
    int allow = 0;
    int decsal = 0;

    /**
     * Creates new form sal
     */
    public sal() {
        initComponents();
        try {
            conn = DB.mycon();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(sal.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel2.setVisible(false);

    }

    public int getMonth() {
        otHours = 0;
        punishments = 0;
        fullDays = 0;
        HalfDays = 0;
        if (month_combo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Select a Month ");
        } else {
            String m = month_combo.getSelectedItem().toString();
            if (m.equals("1-January")) {
                month = 1;
            } else if (m.equals("2-February")) {
                month = 2;
            } else if (m.equals("3-March")) {
                month = 3;
            } else if (m.equals("4-April ")) {
                month = 4;
            } else if (m.equals("5-May")) {
                month = 5;
            } else if (m.equals("6-June")) {
                month = 6;
            } else if (m.equals("7-July")) {
                month = 7;
            } else if (m.equals("8-August")) {
                month = 8;
            } else if (m.equals("9-September")) {
                month = 9;
            } else if (m.equals("10-Octomber")) {
                month = 10;
            } else if (m.equals("11-November")) {
                month = 11;
            } else if (m.equals("12-December")) {
                month = 12;
            }
            return month;
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        search_box = new javax.swing.JTextField();
        name_box = new javax.swing.JLabel();
        id_box = new javax.swing.JLabel();
        bsal_box = new javax.swing.JLabel();
        ot_box = new javax.swing.JLabel();
        full_box = new javax.swing.JLabel();
        half_box = new javax.swing.JLabel();
        Not_box = new javax.swing.JLabel();
        name_box7 = new javax.swing.JLabel();
        name_box8 = new javax.swing.JLabel();
        name_box9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        month_combo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        incompleteAtten_box = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        totWork_box = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        dailyRate_box = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AllocatedSal_box = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        OtPayment_box = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TotSal_box = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        sallary = new javax.swing.JLabel();
        status_box = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dept_box = new javax.swing.JLabel();
        jobtitle_box = new javax.swing.JLabel();
        email_box = new javax.swing.JLabel();
        gender_box = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        allowbox = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        decbox = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Employee No :");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel3.setText("ID :");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel4.setText("Basic Sallary (Rs):");

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel5.setText("OT rate :");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel6.setText("Working Full Days :");

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel7.setText("OT Hours :");

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel8.setText("Half Days :");

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel9.setText("NBT :");

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel10.setText("EPF :");

        jLabel12.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel12.setText("ETF :");

        search_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        search_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_boxActionPerformed(evt);
            }
        });
        search_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_boxKeyReleased(evt);
            }
        });

        name_box.setBackground(new java.awt.Color(255, 255, 255));
        name_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        name_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        id_box.setBackground(new java.awt.Color(255, 255, 255));
        id_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        id_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bsal_box.setBackground(new java.awt.Color(255, 255, 255));
        bsal_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        bsal_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bsal_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ot_box.setBackground(new java.awt.Color(255, 255, 255));
        ot_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        ot_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ot_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        full_box.setBackground(new java.awt.Color(255, 255, 255));
        full_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        full_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        full_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        half_box.setBackground(new java.awt.Color(255, 255, 255));
        half_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        half_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        half_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Not_box.setBackground(new java.awt.Color(255, 255, 255));
        Not_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        Not_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Not_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        name_box7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        name_box7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_box7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        name_box8.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        name_box8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_box8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        name_box9.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        name_box9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_box9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Month :");

        month_combo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        month_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "1-January", "2-February", "3-March", "4-April ", "5-May", "6-June", "7-July", "8-August", "9-September", "10-Octomber", "11-November", "12-December", " " }));
        month_combo.setBorder(null);
        month_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_comboActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel13.setText("Incomplete Attendence :");

        incompleteAtten_box.setBackground(new java.awt.Color(255, 255, 255));
        incompleteAtten_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        incompleteAtten_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incompleteAtten_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(943, 86));

        jLabel14.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Manage Salary");

        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totWork_box.setBackground(new java.awt.Color(255, 255, 255));
        totWork_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        totWork_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totWork_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel15.setText("Total Worked Days :");

        a.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        a.setText("Daily Rate :");

        dailyRate_box.setBackground(new java.awt.Color(255, 255, 255));
        dailyRate_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dailyRate_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel16.setText("Allocated Salary :");

        AllocatedSal_box.setBackground(new java.awt.Color(255, 255, 255));
        AllocatedSal_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AllocatedSal_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel17.setText("OT payment :");

        OtPayment_box.setBackground(new java.awt.Color(255, 255, 255));
        OtPayment_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OtPayment_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel18.setText("Total Sallary :");

        TotSal_box.setBackground(new java.awt.Color(255, 255, 255));
        TotSal_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotSal_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel19.setText("salary + OT");

        sallary.setBackground(new java.awt.Color(255, 255, 255));
        sallary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sallary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        status_box.setBackground(new java.awt.Color(255, 255, 255));
        status_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        status_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel20.setText("Department :");

        jLabel21.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel21.setText("Job Title :");

        jLabel22.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel22.setText("Email :");

        jLabel23.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel23.setText("Gender :");

        jLabel24.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel24.setText("Status :");

        dept_box.setBackground(new java.awt.Color(255, 255, 255));
        dept_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        dept_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dept_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jobtitle_box.setBackground(new java.awt.Color(255, 255, 255));
        jobtitle_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jobtitle_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jobtitle_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        email_box.setBackground(new java.awt.Color(255, 255, 255));
        email_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        email_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gender_box.setBackground(new java.awt.Color(255, 255, 255));
        gender_box.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        gender_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender_box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        allowbox.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        allowbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        allowbox.setText("0");
        allowbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel25.setText("Allowances :");

        jLabel26.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel26.setText("Decrements :");

        decbox.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        decbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        decbox.setText("0");
        decbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setText("Calculate Updated Sallary");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allowbox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel26)
                    .addGap(18, 18, 18)
                    .addComponent(decbox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allowbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(decbox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        jButton4.setText("Update to DB");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Allowances / Decrements");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(month_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel20)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24))
                                    .addGap(39, 39, 39))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22))
                                    .addGap(34, 34, 34))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bsal_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ot_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dept_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jobtitle_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)
                                .addComponent(full_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel9))
                                    .addGap(114, 114, 114)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name_box9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(name_box8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(name_box7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel8))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(half_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Not_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(totWork_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(incompleteAtten_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(a)
                                            .addGap(59, 59, 59))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(TotSal_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dailyRate_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel19))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(AllocatedSal_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(OtPayment_box, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sallary, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 37, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(month_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(full_box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(half_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(totWork_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Not_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(incompleteAtten_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_box7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_box9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name_box8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(id_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bsal_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ot_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(dept_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jobtitle_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(email_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gender_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(status_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a)
                            .addComponent(dailyRate_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(AllocatedSal_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(OtPayment_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(sallary, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TotSal_box, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int min = 0;
        int max = 0;
        int pun = 0;
        TotWorkDays = 0;
        Netsal = 0;
        pay = 0;
        psal = 0;
        ot_rate = 0;
        FullSal = 0;
        decrements = 0;

        Eid = id_box.getText();
        name_box7.setText("0.02 %");
        name_box8.setText("0.02 %");
        name_box9.setText("0.02 %");
        int Cmonth = (getMonth());

        //SUM of OT Hours
        try {
            String sql = "SELECT SUM(`OThours`) FROM `eat" + Eid + "` WHERE `month`=('" + Cmonth + "')";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            String not = jTable1.getValueAt(0, 0).toString();
            System.out.println("not" + not);
            otHours = Integer.parseInt(not);
        } catch (Exception e) {
            System.out.println(e);
        }

        //Count null || punuishments
        try {
            String sql = "SELECT COUNT(count) FROM `eat" + Eid + "` WHERE `out` IS NULL AND `month`=('" + Cmonth + "')";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            String z = jTable1.getValueAt(0, 0).toString();

            punishments = Integer.parseInt(z);
            System.out.println("punishments" + punishments);
        } catch (Exception e) {
            System.out.println(e);

        }

        //Count full days
        try {
            String sql = "SELECT COUNT(`status`) FROM `eat1` WHERE `status`='Full Day'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            String nfull = jTable1.getValueAt(0, 0).toString();
            System.out.println("Full days" + nfull);
            fullDays = Integer.parseInt(nfull);
        } catch (Exception e) {
            System.out.println(e);

        }
        //Count Half days
        try {
            String sql = "SELECT COUNT(`status`) FROM `eat1` WHERE `status`='Half Day'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            String nHalf = jTable1.getValueAt(0, 0).toString();
            System.out.println("Half days" + nHalf);
            HalfDays = Integer.parseInt(nHalf);
        } catch (Exception e) {
            System.out.println(e);

        }

        HalfDays = HalfDays + punishments;
        TotWorkDays = fullDays + HalfDays / 2;

        String tot = String.valueOf(TotWorkDays);
        String full = String.valueOf(fullDays);
        String half = String.valueOf(HalfDays);
        String incomplete_Attend = String.valueOf(punishments);
        String ot = String.valueOf(otHours);

        System.out.println("fullDays:" + fullDays);
        full_box.setText(full);
        System.out.println("HalfDays:" + HalfDays);
        half_box.setText(half);
        System.out.println("Punishment:" + punishments);
        incompleteAtten_box.setText(incomplete_Attend);
        System.out.println("OT hours:" + otHours);
        Not_box.setText(ot);

        totWork_box.setText(tot);

        //Salary Check
        String sal = bsal_box.getText();
        psal = Integer.parseInt(sal);
        pay = (psal / 26);
        String Spay = String.valueOf(pay);
        dailyRate_box.setText(Spay);

        if (TotWorkDays > 26) {
            Netsal = psal;
        } else {
            Netsal = pay * TotWorkDays;
        }
        String TNetsal = String.valueOf(Netsal);
        AllocatedSal_box.setText(Spay);

        //Ot payment
        ot_rate = Integer.parseInt(ot_box.getText());
        System.out.println("ot_rate:" + ot_rate);

        otpay = ot_rate * otHours;
        OtPayment = String.valueOf(otpay);
        OtPayment_box.setText(OtPayment);

//        //Full salary
//        decrements = ((otpay + Netsal) * (6 / 100));
        int fullSal = (otpay + Netsal);
        System.out.println(fullSal);
        String fsal = String.valueOf(fullSal);
        int dec = (fullSal * 6) / 100;
        System.out.println(dec);

        int NetTotal = fullSal - dec;
        System.out.println(NetTotal);

        sallary.setText(fsal);
        FullSal = otpay + Netsal - (decrements);
        String TfullSal = String.valueOf(NetTotal);
        TotSal_box.setText(TfullSal);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void search_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_boxKeyReleased

        // TODO add your handling code here:
        String id = search_box.getText();
        String b = "";
        if (!id.equals(b)) {
            try {
                String sql = "Select id,first_name,salary,ot_rate,Department,job_title,Email,gender,Status from staff_information where id=('" + id + "')";
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));;
                String i = jTable1.getValueAt(0, 0).toString();
                String name = jTable1.getValueAt(0, 1).toString();
                String sal = jTable1.getValueAt(0, 2).toString();
                String ot = jTable1.getValueAt(0, 3).toString();
                String dept = jTable1.getValueAt(0, 4).toString();
                String jtitle = jTable1.getValueAt(0, 5).toString();
                String mail = jTable1.getValueAt(0, 6).toString();
                String gender = jTable1.getValueAt(0, 7).toString();
                String status = jTable1.getValueAt(0, 8).toString();

                id_box.setText(i);
                name_box.setText(name);
                bsal_box.setText(sal);
                ot_box.setText(ot);
                dept_box.setText(dept);
                jobtitle_box.setText(jtitle);
                email_box.setText(mail);
                gender_box.setText(gender);
                status_box.setText(status);

            } catch (Exception e) {
            }
        } else {
            Not_box.setText("");
            bsal_box.setText("");;
            full_box.setText("");;
            half_box.setText("");;
            id_box.setText("");;
            incompleteAtten_box.setText("");;
            month_combo.setSelectedIndex(0);
            name_box.setText("");;
            name_box7.setText("");;
            name_box8.setText("");;
            name_box9.setText("");;
            ot_box.setText("");;
            dailyRate_box.setText("");
            totWork_box.setText("");
            AllocatedSal_box.setText("");
            OtPayment_box.setText("");
            TotSal_box.setText("");
            dept_box.setText("");
            jobtitle_box.setText("");
            email_box.setText("");
            gender_box.setText("");
            status_box.setText("");
            name_box7.setText("");
            name_box8.setText("");
            name_box9.setText("");
            sallary.setText("");
        }

    }//GEN-LAST:event_search_boxKeyReleased

    private void month_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_month_comboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        this.dispose();
//        hr h = new hr();
//        h.setVisible(true);
    new employee().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String a = allowbox.getText();
        allow = Integer.parseInt(a);
        String b = decbox.getText();
        decsal = Integer.parseInt(b);

        String c = TotSal_box.getText();
        int netsal = Integer.parseInt(c);
        int upsal = (netsal + allow) - decsal;
        String up = String.valueOf(upsal);
        allowbox.setText("0");
        decbox.setText("0");
        TotSal_box.setText(up);
        System.out.println("allow" + allow);
        System.out.println("dec" + decsal);
        System.out.println("netsal" + netsal);
        System.out.println("upsal" + upsal);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int Cmonth = getMonth();
        Eid = id_box.getText();
        String sal = TotSal_box.getText();
        if (sal.equals("") || (Eid.equals(""))) {
            JOptionPane.showMessageDialog(null, "No Proper Data !");
        } else {
            int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Save Sallary Info?");
            if (x == 0) {
                System.out.println("Cmonth :" + Cmonth);
                System.out.println("Eid :" + Eid);
                System.out.println("sal :" + sal);

                try {
                    String sql = "INSERT INTO `salary`(`eid`, `month`, `sallary`) VALUES (('" + Eid + "'),('" + Cmonth + "'),('" + sal + "'))";
                    pst = conn.prepareStatement(sql);
                    pst.execute();
                    System.out.println(sql);

                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            jPanel2.setVisible(true);
        } else {
            jPanel2.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void search_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AllocatedSal_box;
    private javax.swing.JLabel Not_box;
    private javax.swing.JLabel OtPayment_box;
    private javax.swing.JLabel TotSal_box;
    private javax.swing.JLabel a;
    private javax.swing.JTextField allowbox;
    private javax.swing.JLabel bsal_box;
    private javax.swing.JLabel dailyRate_box;
    private javax.swing.JTextField decbox;
    private javax.swing.JLabel dept_box;
    private javax.swing.JLabel email_box;
    private javax.swing.JLabel full_box;
    private javax.swing.JLabel gender_box;
    private javax.swing.JLabel half_box;
    private javax.swing.JLabel id_box;
    private javax.swing.JLabel incompleteAtten_box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jobtitle_box;
    private javax.swing.JComboBox<String> month_combo;
    private javax.swing.JLabel name_box;
    private javax.swing.JLabel name_box7;
    private javax.swing.JLabel name_box8;
    private javax.swing.JLabel name_box9;
    private javax.swing.JLabel ot_box;
    private javax.swing.JLabel sallary;
    private javax.swing.JTextField search_box;
    private javax.swing.JLabel status_box;
    private javax.swing.JLabel totWork_box;
    // End of variables declaration//GEN-END:variables
}
